name: Deploy Django to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py check
          python manage.py test

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run deployment script on Azure VM
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $username = '${{ secrets.AZURE_VM_USER }}'
            $password = ConvertTo-SecureString '${{ secrets.AZURE_VM_PASSWORD }}' -AsPlainText -Force
            $cred = New-Object System.Management.Automation.PSCredential($username, $password)
            Invoke-Command -ComputerName ${{ secrets.AZURE_VM_HOST }} -Credential $cred -ScriptBlock {
              if (!(Test-Path C:\inetpub\django-learner1)) { New-Item -Path C:\inetpub\django-learner1 -ItemType Directory }
              cd C:\inetpub\django-learner1
              if (!(Test-Path .git)) { git clone https://github.com/${{ github.repository }} . } else { git pull origin main }
              pip install -r requirements.txt
              python manage.py migrate --noinput
              python manage.py collectstatic --noinput
              nssm restart django
            }
          azPSVersion: 'latest'
